import { useQuery } from '@tanstack/react-query';
import { Activity, ArrowDownRight, ArrowUpRight, Clock3, MoreHorizontal, ShieldCheck, TicketCheck, Users } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getMetrics, getTickets } from '../lib/api';
import { PriorityBadge, StatusBadge } from '../components/StatusBadge';
import { Link } from 'react-router-dom';
import { formatDate } from '../lib/utils';

const chartData = [{ day: '29 sep', creados: 9, resueltos: 7 }, { day: '30 sep', creados: 14, resueltos: 11 }, { day: '1 oct', creados: 8, resueltos: 12 }, { day: '2 oct', creados: 17, resueltos: 10 }, { day: '3 oct', creados: 12, resueltos: 15 }, { day: '4 oct', creados: 16, resueltos: 13 }, { day: '5 oct', creados: 11, resueltos: 14 }];
const workload = [{ name: 'Marta Ruiz', initials: 'MR', color: 'from-blue-500 to-cyan-400', count: 12, width: '80%' }, { name: 'Álex Gil', initials: 'AG', color: 'from-violet-500 to-fuchsia-400', count: 9, width: '60%' }, { name: 'Sara León', initials: 'SL', color: 'from-amber-500 to-orange-400', count: 7, width: '47%' }, { name: 'Jon Pérez', initials: 'JP', color: 'from-emerald-500 to-teal-400', count: 4, width: '27%' }];

export function Dashboard() {
  const { data: metrics, isLoading } = useQuery({ queryKey: ['metrics'], queryFn: getMetrics });
  const { data: tickets = [] } = useQuery({ queryKey: ['tickets'], queryFn: getTickets });
  const cards = metrics ? [
    { label: 'Tickets abiertos', value: metrics.open, delta: `${Math.abs(metrics.delta.open)}%`, good: metrics.delta.open < 0, icon: TicketCheck, helper: 'frente a la semana anterior' },
    { label: 'Primera respuesta', value: metrics.firstResponse, delta: `${Math.abs(metrics.delta.response)}%`, good: true, icon: Clock3, helper: 'objetivo: menos de 1 h' },
    { label: 'Tiempo de resolución', value: metrics.resolution, delta: `${Math.abs(metrics.delta.resolution)}%`, good: metrics.delta.resolution < 0, icon: Activity, helper: 'media de los últimos 7 días' },
    { label: 'Cumplimiento de SLA', value: `${metrics.sla}%`, delta: `${Math.abs(metrics.delta.sla)}%`, good: metrics.delta.sla > 0, icon: ShieldCheck, helper: 'objetivo mensual: 95%' },
  ] : [];
  const today = new Intl.DateTimeFormat('es-ES', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date());
  return <div className="mx-auto max-w-[1600px] p-4 sm:p-7 lg:p-8">
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm font-medium capitalize text-electric-600">{today}</p><h1 className="text-2xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-[28px]">Resumen de soporte</h1><p className="mt-1 text-sm text-slate-500">Datos de la última semana en Lumen Norte.</p></div><select aria-label="Periodo" className="input w-auto"><option>Últimos 7 días</option><option>Últimos 30 días</option></select></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Métricas principales">{isLoading ? Array.from({ length: 4 }).map((_, i) => <div key={i} className="surface h-36 animate-pulse bg-slate-100 dark:bg-slate-800" />) : cards.map(({ label, value, delta, good, icon: Icon, helper }) => <article key={label} className="surface p-5"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-electric-600 dark:bg-blue-950/50"><Icon className="h-5 w-5" /></div><span className={`flex items-center text-xs font-semibold ${good ? 'text-emerald-600' : 'text-rose-600'}`}>{good ? <ArrowDownRight className="h-3.5 w-3.5" /> : <ArrowUpRight className="h-3.5 w-3.5" />}{delta}</span></div><div className="mt-4 text-2xl font-bold tracking-tight text-slate-950 dark:text-white">{value}</div><div className="mt-1 text-xs font-medium text-slate-500">{label}</div><div className="mt-1 text-[10px] text-slate-400">{helper}</div></article>)}</section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1.7fr_1fr]"><article className="surface min-w-0 p-5"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-semibold">Volumen de tickets</h2><p className="text-xs text-slate-400">Creados frente a resueltos</p></div><button aria-label="Más opciones"><MoreHorizontal className="text-slate-400" /></button></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="blue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1677ff" stopOpacity={.25}/><stop offset="100%" stopColor="#1677ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf4" /><XAxis dataKey="day" axisLine={false} tickLine={false} fontSize={10} tickMargin={10} /><YAxis axisLine={false} tickLine={false} fontSize={10} width={24}/><Tooltip contentStyle={{ borderRadius: 12, borderColor: '#e2e8f0', fontSize: 12 }} /><Area type="monotone" dataKey="creados" stroke="#1677ff" strokeWidth={2.5} fill="url(#blue)" /><Area type="monotone" dataKey="resueltos" stroke="#22c55e" strokeWidth={2} fill="transparent" /></AreaChart></ResponsiveContainer></div><div className="mt-3 flex justify-center gap-5 text-[11px] text-slate-500"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-electric-500"/>Creados</span><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-green-500"/>Resueltos</span></div></article>
    <article className="surface p-5"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-semibold">Carga del equipo</h2><p className="text-xs text-slate-400">Tickets activos por agente</p></div><Users className="h-4.5 w-4.5 text-slate-400" /></div><div className="space-y-5">{workload.map((agent) => <div key={agent.name}><div className="mb-2 flex items-center gap-3"><div className={`grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br ${agent.color} text-[10px] font-bold text-white`}>{agent.initials}</div><span className="flex-1 text-xs font-semibold">{agent.name}</span><span className="text-xs font-bold">{agent.count}</span></div><div className="ml-11 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-electric-500" style={{ width: agent.width }} /></div></div>)}</div><Link to="/team" className="mt-6 block text-center text-xs font-semibold text-electric-600">Ver todo el equipo →</Link></article></section>
    <section className="surface mt-4 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><div><h2 className="font-semibold">Actividad reciente</h2><p className="text-xs text-slate-400">Tickets que requieren atención</p></div><Link to="/tickets" className="text-xs font-semibold text-electric-600">Ver todos</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400 dark:border-slate-800"><th className="px-5 py-3 font-semibold">Ticket</th><th className="px-4 py-3 font-semibold">Solicitante</th><th className="px-4 py-3 font-semibold">Prioridad</th><th className="px-4 py-3 font-semibold">Estado</th><th className="px-4 py-3 font-semibold">Agente</th><th className="px-5 py-3 text-right font-semibold">Actualizado</th></tr></thead><tbody>{tickets.slice(0, 5).map((ticket) => <tr key={ticket.code} className="border-b border-slate-100 text-xs transition last:border-0 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800/50"><td className="px-5 py-3.5"><Link to={`/tickets/${ticket.code}`} className="font-semibold text-slate-800 hover:text-electric-600 dark:text-slate-100"><span className="mr-2 text-[10px] font-bold text-electric-600">{ticket.code}</span>{ticket.title}</Link></td><td className="px-4 py-3.5 text-slate-500">{ticket.requester}</td><td className="px-4 py-3.5"><PriorityBadge priority={ticket.priority}/></td><td className="px-4 py-3.5"><StatusBadge status={ticket.status}/></td><td className="px-4 py-3.5 text-slate-500">{ticket.assignee ?? 'Sin asignar'}</td><td className="px-5 py-3.5 text-right text-slate-400">{formatDate(ticket.updatedAt)}</td></tr>)}</tbody></table></div></section>
  </div>;
}

