import { useState } from 'react';
import { ArrowRight, CheckCircle2, LockKeyhole } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Logo } from '../components/Logo';
import { login } from '../lib/api';

export function Login() {
  const navigate = useNavigate();
  const [email, setEmail] = useState('admin@supportflow.local');
  const [password, setPassword] = useState('SupportFlow2026!');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { await login(email, password); navigate('/'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo iniciar sesión.'); } finally { setLoading(false); } };
  return <main className="grid min-h-screen bg-white dark:bg-navy-950 lg:grid-cols-2"><section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><Logo/><div className="mt-12"><p className="text-xs font-bold uppercase tracking-[.16em] text-electric-600">Bienvenido de nuevo</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Accede a tu espacio</h1><p className="mt-2 text-sm text-slate-500">Gestiona solicitudes y ayuda a tus clientes desde un único lugar.</p></div><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-xs font-semibold">Correo electrónico</span><input className="input" type="email" autoComplete="email" required value={email} onChange={(event)=>setEmail(event.target.value)}/></label><label className="block"><span className="mb-2 block text-xs font-semibold">Contraseña</span><input className="input" type="password" autoComplete="current-password" required value={password} onChange={(event)=>setPassword(event.target.value)}/></label>{error && <div role="alert" className="rounded-xl bg-rose-50 p-3 text-xs font-medium text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">{error}</div>}<button className="btn-primary w-full" disabled={loading}>{loading ? 'Accediendo…' : 'Iniciar sesión'}<ArrowRight className="h-4 w-4"/></button><button type="button" className="w-full text-center text-xs font-semibold text-electric-600">He olvidado mi contraseña</button></form><p className="mt-10 text-center text-[10px] text-slate-400">Entorno de demostración · Consulta las cuentas en el README</p></div></section><aside className="hidden items-center justify-center overflow-hidden bg-navy-950 p-12 text-white lg:flex"><div className="max-w-lg"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-500/15 text-blue-400"><LockKeyhole className="h-7 w-7"/></div><h2 className="mt-8 text-4xl font-bold leading-tight">Soporte excepcional, sin perder el control.</h2><p className="mt-5 leading-7 text-slate-300">Centraliza cada conversación, cumple tus acuerdos de servicio y convierte los datos en mejores decisiones.</p><ul className="mt-8 space-y-4 text-sm text-slate-300">{['Aislamiento seguro por organización','Permisos aplicados en la API','SLA y actividad en tiempo real'].map((item)=><li key={item} className="flex items-center gap-3"><CheckCircle2 className="h-5 w-5 text-blue-400"/>{item}</li>)}</ul></div></aside></main>;
}
