import { useState } from 'react';
import { ArrowRight, Clock3, MessageSquareText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Logo } from '../components/Logo';
import { login } from '../lib/api';

export function Login() {
  const navigate = useNavigate();
  const [email, setEmail] = useState('admin@supportflow.local');
  const [password, setPassword] = useState('SupportFlow2026!');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { await login(email, password); navigate('/'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo iniciar sesión.'); } finally { setLoading(false); } };
  return <main className="grid min-h-screen bg-white dark:bg-navy-950 lg:grid-cols-2"><section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><Logo/><div className="mt-12"><h1 className="text-3xl font-bold tracking-tight">Inicia sesión</h1><p className="mt-2 text-sm text-slate-500">Accede a la mesa de ayuda de Lumen Norte.</p></div><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-xs font-semibold">Correo electrónico</span><input className="input" type="email" autoComplete="email" required value={email} onChange={(event)=>setEmail(event.target.value)}/></label><label className="block"><span className="mb-2 block text-xs font-semibold">Contraseña</span><input className="input" type="password" autoComplete="current-password" required value={password} onChange={(event)=>setPassword(event.target.value)}/></label>{error && <div role="alert" className="rounded-xl bg-rose-50 p-3 text-xs font-medium text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">{error}</div>}<button className="btn-primary w-full" disabled={loading}>{loading ? 'Accediendo…' : 'Iniciar sesión'}<ArrowRight className="h-4 w-4"/></button><button type="button" className="w-full text-center text-xs font-semibold text-electric-600">He olvidado mi contraseña</button></form><p className="mt-10 text-center text-[10px] text-slate-400">Demo local · Las cuentas están documentadas en el README</p></div></section><aside className="hidden items-center justify-center overflow-hidden bg-navy-950 p-12 text-white lg:flex"><div className="w-full max-w-lg"><p className="text-sm font-semibold text-blue-400">Actividad reciente</p><h2 className="mt-3 text-3xl font-bold leading-tight">Lo importante, a primera vista.</h2><div className="mt-8 space-y-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center gap-3"><MessageSquareText className="h-5 w-5 text-blue-400"/><div><p className="text-sm font-semibold">Marta respondió a SUP-1048</p><p className="mt-1 text-xs text-slate-400">Hace 12 minutos · Respuesta pública</p></div></div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center gap-3"><Clock3 className="h-5 w-5 text-amber-400"/><div><p className="text-sm font-semibold">SUP-1045 ha superado su SLA</p><p className="mt-1 text-xs text-slate-400">Facturación · Prioridad alta</p></div></div></div></div></div></aside></main>;
}
