import { ArrowLeft, CheckCircle2, Paperclip } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';

export function NewTicket() {
  const [created, setCreated] = useState(false);
  if (created) return <div className="mx-auto max-w-3xl p-4 sm:p-8"><div className="surface p-10 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-500"/><h1 className="mt-4 text-xl font-bold">Ticket creado en la demo</h1><p className="mt-2 text-sm text-slate-500">Se ha simulado el alta como SUP-1049. El modo conectado envía estos datos a Laravel.</p><Link to="/tickets" className="btn-primary mt-6">Volver a la bandeja</Link></div></div>;
  return <div className="mx-auto max-w-3xl p-4 sm:p-8"><Link to="/tickets" className="mb-5 inline-flex items-center gap-2 text-xs font-semibold text-slate-500"><ArrowLeft className="h-4 w-4"/>Cancelar y volver</Link><div className="surface p-6 sm:p-8"><h1 className="text-2xl font-bold">Crear un ticket</h1><p className="mt-1 text-sm text-slate-500">Describe el problema con detalle para acelerar su resolución.</p><form className="mt-7 space-y-5" onSubmit={(event) => { event.preventDefault(); setCreated(true); }}><label className="block"><span className="mb-2 block text-xs font-semibold">Asunto</span><input required className="input" placeholder="Ej.: El webhook devuelve un error 401"/></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-semibold">Categoría</span><select required className="input" defaultValue=""><option value="" disabled>Selecciona una categoría</option><option>Cuenta</option><option>Facturación</option><option>Integraciones</option></select></label><label><span className="mb-2 block text-xs font-semibold">Prioridad</span><select className="input"><option>Media</option><option>Baja</option><option>Alta</option><option>Urgente</option></select></label></div><label className="block"><span className="mb-2 block text-xs font-semibold">Descripción</span><textarea required className="input min-h-40" placeholder="Indica cuándo empezó, qué esperabas y cómo se puede reproducir."/></label><label className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-200 p-6 text-xs font-medium text-slate-500 hover:border-electric-500 hover:text-electric-600 dark:border-slate-700"><Paperclip className="h-4 w-4"/>Adjuntar un archivo<input type="file" className="sr-only"/></label><p className="text-[11px] text-slate-400">En modo demo el alta se simula en el navegador y no se conserva al recargar.</p><div className="flex justify-end gap-3 border-t border-slate-100 pt-5 dark:border-slate-800"><Link to="/tickets" className="btn-secondary">Cancelar</Link><button className="btn-primary" type="submit">Crear ticket</button></div></form></div></div>;
}

