import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, CalendarClock, Check, Link2, MessageSquare, Paperclip, Send, ShieldAlert, UserRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getTicket } from '../lib/api';
import { PriorityBadge, StatusBadge } from '../components/StatusBadge';

const timeline = [
  { actor: 'Laura Martín', text: 'creó el ticket', time: '10:42', kind: 'event' },
  { actor: 'Sistema', text: 'asignó el ticket al equipo Integraciones', time: '10:42', kind: 'event' },
  { actor: 'Marta Ruiz', text: 'Hola Laura, estamos revisando los registros de la sincronización. Te mantendré informada.', time: '10:55', kind: 'comment' },
  { actor: 'Marta Ruiz', text: 'El token del ERP expiró durante la tarea nocturna. Renovar credenciales y relanzar el lote.', time: '11:08', kind: 'note' },
];

export function TicketDetail() {
  const { code = '' } = useParams();
  const { data: ticket, isLoading } = useQuery({ queryKey: ['ticket', code], queryFn: () => getTicket(code) });
  if (isLoading) return <div className="p-12 text-sm text-slate-400">Cargando ticket…</div>;
  if (!ticket) return <div className="p-12"><h1 className="font-bold">Ticket no encontrado</h1><Link className="text-sm text-electric-600" to="/tickets">Volver a tickets</Link></div>;
  return <div className="mx-auto max-w-[1500px] p-4 sm:p-7 lg:p-8"><Link to="/tickets" className="mb-5 inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-electric-600"><ArrowLeft className="h-4 w-4"/>Volver a tickets</Link><div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="mb-2 flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-electric-600">{ticket.code}</span><StatusBadge status={ticket.status}/><PriorityBadge priority={ticket.priority}/></div><h1 className="text-2xl font-bold tracking-tight">{ticket.title}</h1><p className="mt-2 text-sm text-slate-500">Creado por {ticket.requester} · hace 2 horas · vía portal</p></div><div className="flex gap-2"><button className="btn-secondary">Marcar pendiente</button><button className="btn-primary"><Check className="h-4 w-4"/>Resolver ticket</button></div></div>
  <div className="grid gap-5 xl:grid-cols-[1fr_320px]"><section className="space-y-5"><article className="surface p-5"><h2 className="mb-3 text-sm font-semibold">Descripción</h2><p className="text-sm leading-7 text-slate-600 dark:text-slate-300">{ticket.description ?? 'El solicitante no ha incluido detalles adicionales.'}</p><div className="mt-4 flex items-center gap-2 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="grid h-9 w-9 place-items-center rounded-lg bg-rose-50 text-rose-600 dark:bg-rose-950/50"><Paperclip className="h-4 w-4"/></div><div className="flex-1"><div className="text-xs font-semibold">error-sincronizacion.pdf</div><div className="text-[10px] text-slate-400">428 KB · PDF</div></div><button className="text-xs font-semibold text-electric-600">Descargar</button></div></article>
  <article className="surface p-5"><div className="mb-5 flex items-center gap-2"><MessageSquare className="h-4 w-4 text-electric-600"/><h2 className="text-sm font-semibold">Conversación y actividad</h2></div><div className="space-y-5">{timeline.map((item, index) => item.kind === 'event' ? <div key={index} className="flex items-center gap-3 text-[11px] text-slate-400"><span className="h-1.5 w-1.5 rounded-full bg-slate-300"/><span><b className="text-slate-600 dark:text-slate-300">{item.actor}</b> {item.text}</span><span className="ml-auto">{item.time}</span></div> : <div key={index} className={`rounded-xl border p-4 ${item.kind === 'note' ? 'border-amber-200 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/30' : 'border-slate-200 dark:border-slate-700'}`}><div className="mb-2 flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-full bg-electric-500 text-[9px] font-bold text-white">MR</div><span className="text-xs font-semibold">{item.actor}</span>{item.kind === 'note' && <span className="chip bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300">Nota interna</span>}<span className="ml-auto text-[10px] text-slate-400">{item.time}</span></div><p className="pl-9 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.text}</p></div>)}</div><div className="mt-6 rounded-xl border border-slate-200 dark:border-slate-700"><div className="flex border-b border-slate-200 px-3 dark:border-slate-700"><button className="border-b-2 border-electric-500 px-3 py-2.5 text-xs font-semibold text-electric-600">Respuesta pública</button><button className="px-3 py-2.5 text-xs font-medium text-slate-400">Nota interna</button></div><textarea className="min-h-28 w-full resize-y bg-transparent p-4 text-sm outline-none" placeholder="Escribe una respuesta…"/><div className="flex items-center justify-between p-3"><button className="text-slate-400" aria-label="Adjuntar archivo"><Paperclip className="h-4 w-4"/></button><button className="btn-primary py-2"><Send className="h-4 w-4"/>Enviar respuesta</button></div></div></article></section>
  <aside className="space-y-4"><article className="surface p-5"><h2 className="mb-4 text-sm font-semibold">Detalles</h2><dl className="space-y-4 text-xs"><div><dt className="mb-1 text-slate-400">Solicitante</dt><dd className="flex items-center gap-2 font-semibold"><UserRound className="h-3.5 w-3.5 text-slate-400"/>{ticket.requester}</dd></div><div><dt className="mb-1 text-slate-400">Agente asignado</dt><dd className="font-semibold">{ticket.assignee ?? 'Sin asignar'}</dd></div><div><dt className="mb-1 text-slate-400">Equipo</dt><dd className="font-semibold">{ticket.team}</dd></div><div><dt className="mb-1 text-slate-400">Categoría</dt><dd className="font-semibold">{ticket.category}</dd></div></dl></article><article className={`surface p-5 ${ticket.sla === 'risk' ? 'border-amber-200 dark:border-amber-900' : ''}`}><div className="mb-3 flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-amber-500"/><h2 className="text-sm font-semibold">Acuerdo de servicio</h2></div><div className="mb-2 flex items-end justify-between"><div><div className="text-[10px] text-slate-400">Resolución objetivo</div><div className="mt-1 text-sm font-bold">Hoy, 14:42</div></div><span className="text-xs font-semibold text-amber-600">2 h 18 min</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full w-3/4 rounded-full bg-amber-500"/></div><div className="mt-2 flex items-center gap-1.5 text-[10px] text-slate-400"><CalendarClock className="h-3 w-3"/>SLA: Incidencias urgentes (4 h)</div></article><article className="surface p-5"><div className="mb-3 flex items-center gap-2"><Link2 className="h-4 w-4 text-slate-400"/><h2 className="text-sm font-semibold">Artículos sugeridos</h2></div><a href="#article" className="block rounded-lg bg-slate-50 p-3 text-xs font-medium hover:text-electric-600 dark:bg-slate-800">Cómo renovar credenciales de una integración</a></article></aside></div></div>;
}

