import { useQuery } from '@tanstack/react-query';
import { Download, Filter, Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { getTickets } from '../lib/api';
import { formatDate } from '../lib/utils';
import { PriorityBadge, StatusBadge } from '../components/StatusBadge';

export function Tickets() {
  const { data: tickets = [], isLoading } = useQuery({ queryKey: ['tickets'], queryFn: getTickets });
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('todos');
  const filtered = useMemo(() => tickets.filter((ticket) => (status === 'todos' || ticket.status === status) && `${ticket.code} ${ticket.title} ${ticket.requester}`.toLowerCase().includes(search.toLowerCase())), [tickets, search, status]);
  return <div className="mx-auto max-w-[1600px] p-4 sm:p-7 lg:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">Tickets</h1><p className="mt-1 text-sm text-slate-500">Gestiona y prioriza todas las solicitudes de soporte.</p></div><button className="btn-secondary"><Download className="h-4 w-4"/>Exportar CSV</button></div>
    <div className="surface overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 dark:border-slate-800 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} className="input pl-9" placeholder="Buscar por ID, asunto o solicitante…"/></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="input sm:w-44" aria-label="Filtrar estado"><option value="todos">Todos los estados</option><option value="nuevo">Nuevo</option><option value="abierto">Abierto</option><option value="pendiente">Pendiente</option><option value="resuelto">Resuelto</option><option value="cerrado">Cerrado</option></select><button className="btn-secondary"><Filter className="h-4 w-4"/>Más filtros</button><button className="btn-secondary px-3" aria-label="Configurar columnas"><SlidersHorizontal className="h-4 w-4"/></button></div>
    {isLoading ? <div className="p-12 text-center text-sm text-slate-400">Cargando tickets…</div> : filtered.length === 0 ? <div className="p-16 text-center"><div className="text-sm font-semibold">No hay resultados</div><p className="mt-1 text-xs text-slate-400">Prueba con otro término o elimina los filtros.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead><tr className="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400 dark:border-slate-800"><th className="px-5 py-3">ID y asunto</th><th className="px-4 py-3">Solicitante</th><th className="px-4 py-3">Prioridad</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Equipo / Agente</th><th className="px-5 py-3 text-right">Actualizado</th></tr></thead><tbody>{filtered.map((ticket) => <tr key={ticket.code} className="border-b border-slate-100 text-xs hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800/40"><td className="px-5 py-4"><Link to={`/tickets/${ticket.code}`} className="block font-semibold hover:text-electric-600"><span className="mb-1 block text-[10px] text-electric-600">{ticket.code}</span>{ticket.title}</Link></td><td className="px-4 py-4 text-slate-500">{ticket.requester}</td><td className="px-4 py-4"><PriorityBadge priority={ticket.priority}/></td><td className="px-4 py-4"><StatusBadge status={ticket.status}/></td><td className="px-4 py-4"><div className="font-medium">{ticket.assignee ?? 'Sin asignar'}</div><div className="mt-0.5 text-[10px] text-slate-400">{ticket.team}</div></td><td className="px-5 py-4 text-right text-slate-400">{formatDate(ticket.updatedAt)}</td></tr>)}</tbody></table></div>}<div className="flex items-center justify-between border-t border-slate-100 px-5 py-3 text-xs text-slate-400 dark:border-slate-800"><span>{filtered.length} de {tickets.length} tickets</span><span>Página 1 de 1</span></div></div>
  </div>;
}

