import { metrics, tickets } from '../data/demo';
import type { DashboardMetrics, Ticket } from '../types';

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const demoMode = import.meta.env.MODE === 'test' || import.meta.env.VITE_DEMO_MODE === 'true';
const apiUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:8000/api/v1';

type ApiTicket = { id: number; code: string; title: string; description?: string; status: Ticket['status']; requester?: { name: string }; category?: { name: string }; priority?: { name: Ticket['priority'] }; assignee?: { name: string } | null; team?: { name: string } | null; updated_at: string; sla?: { breached: boolean; due_at: string | null } };
const headers = () => ({ Accept: 'application/json', Authorization: `Bearer ${localStorage.getItem('supportflow_token') ?? ''}` });
async function request<T>(path: string): Promise<T> { const response = await fetch(`${apiUrl}${path}`, { headers: headers() }); if (!response.ok) throw new Error(response.status === 401 ? 'Tu sesión ha caducado.' : 'No se pudieron cargar los datos.'); return response.json() as Promise<T>; }
export async function login(email: string, password: string): Promise<void> { const response = await fetch(`${apiUrl}/auth/login`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) throw new Error('El correo o la contraseña no son correctos.'); const data = await response.json() as { token: string }; localStorage.setItem('supportflow_token', data.token); }
const fromApi = (ticket: ApiTicket): Ticket => ({ id: ticket.id, code: ticket.code, title: ticket.title, description: ticket.description, requester: ticket.requester?.name ?? 'Sin solicitante', category: ticket.category?.name ?? 'General', priority: ticket.priority?.name ?? 'Media', status: ticket.status, assignee: ticket.assignee?.name ?? null, team: ticket.team?.name ?? 'Sin equipo', updatedAt: ticket.updated_at, sla: ticket.sla?.breached ? 'breached' : ticket.sla?.due_at && new Date(ticket.sla.due_at).getTime() - Date.now() < 3_600_000 ? 'risk' : 'ok' });

export async function getTickets(): Promise<Ticket[]> { if (demoMode) { await sleep(250); return tickets; } const response = await request<{ data: ApiTicket[] }>('/tickets'); return response.data.map(fromApi); }
export async function getTicket(code: string): Promise<Ticket | undefined> { if (demoMode) { await sleep(180); return tickets.find((ticket) => ticket.code === code); } const list = await getTickets(); const match = list.find((ticket) => ticket.code === code); if (!match) return undefined; const response = await request<{ data: ApiTicket }>(`/tickets/${match.id}`); return fromApi(response.data); }
export async function getMetrics(): Promise<DashboardMetrics> { if (demoMode) { await sleep(180); return metrics; } const data = await request<{ tickets_by_status: Record<string, number>; average_first_response_minutes: number; average_resolution_hours: number; sla_compliance: number }>('/dashboard'); return { open: (data.tickets_by_status.nuevo ?? 0) + (data.tickets_by_status.abierto ?? 0) + (data.tickets_by_status.pendiente ?? 0), firstResponse: `${Math.round(data.average_first_response_minutes)} min`, resolution: `${data.average_resolution_hours.toFixed(1)} h`, sla: data.sla_compliance, delta: { open: 0, response: 0, resolution: 0, sla: 0 } }; }
